<?php


require_once __DIR__ . '/../auth_check.php';
require_once __DIR__ . '/../protect.php';
include '../../connect_db/config.php'; 
date_default_timezone_set('Asia/Kuala_Lumpur');

// Start session if not already started
if (session_status() == PHP_SESSION_NONE) {
  session_start();
}


$startDate = $_GET['start_date'] ?? date('Y-m-01');
$endDateRaw = $_GET['end_date'] ?? date('Y-m-t');
$endDate = $endDateRaw . ' 23:59:59';


$sql = "SELECT o.order_id, o.order_at, p.product_id, p.product_name, oi.quantity, oi.price
        FROM orders o
        JOIN order_items oi ON o.order_id = oi.order_id
        JOIN product p ON oi.product_id = p.product_id
        WHERE o.order_at BETWEEN ? AND ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $startDate, $endDate);
$stmt->execute();
$result = $stmt->get_result();

$salesData = [];
$totalSales = 0;
$totalOrders = 0;
$orderIDs = [];

while ($row = $result->fetch_assoc()) {
    $pid = $row['product_id'];
    $name = $row['product_name'];
    $amount = $row['quantity'] * $row['price'];

    if (!isset($salesData[$pid])) {
      $salesData[$pid] = [
          'product_id' => $pid,
          'product_name' => $name,
          'price' => $row['price'],
          'quantity' => 0,
          'revenue' => 0
        ];
      }
    
    $salesData[$pid]['quantity'] = ($salesData[$pid]['quantity'] ?? 0) + $row['quantity'];
    $salesData[$pid]['revenue'] = ($salesData[$pid]['revenue'] ?? 0) + $amount;


    $totalSales += $amount;
    $orderIDs[$row['order_id']] = true;
}
$totalOrders = count($orderIDs);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VeroSports</title>
    
    <link rel="stylesheet" href="../Header_And_Footer/header.css">
    <link rel="stylesheet" href="../sidebar/sidebar.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    body {
        color: #333;
    }

    .contain{
        display: flex;
        align-items: flex-start;
        gap: 20px;
        width: 100%;
        padding-left: 250px;
    }
    
    .report-box {
      background: white;
      padding: 30px;
      border-radius: 10px;
      box-shadow: 0 0 10px #ccc; 
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      width: 99%;
      height: 100%;
      position: relative;
      top: 100px;
    }
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      border-bottom: 2px solid #000;
      padding-bottom: 10px;
    }
    .header img {
      height: 60px;
    }
    h2 {
      margin-top: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    table th{
      background-color: lightgray;
    }

    table th, table td {
      border: 1px solid gray;
      padding: 10px;
      text-align: left;
    }
    .summary {
      margin-top: 20px;
    }
    .filter {
      margin-bottom: 40px;
      margin-top: 20px;
    }

    .filter button{
      background-color: lightgray;
      padding: 4px 20px;
      border-radius: 2px;
      border: none;
      margin-left: 10px;
    }

    .download-btn{
      padding: 10px 20px;
      margin: 20px;
      display: flex;
      justify-content: center;
      text-decoration: none;
    }

    .download-btn button{
      width: 20%;
      background-color: rgb(0, 187, 0);
      padding: 10px 20px;
      font-weight: bold;
      color: white;
      border-radius: 10px;
      border:none;
    }

    .download-btn button:hover{
      background-color: rgb(0, 131, 0);
    }
  </style>
</head>
<body>
      <?php include __DIR__ . '/../Header_And_Footer/header.php'; ?>

      <div class="contain">
          <?php include __DIR__ . '/../sidebar/sidebar.php'; ?>
  

    <div class="report-box">
      <div class="header">
        <img src="../../upload/VeroSports.jpeg" alt="VeroSports Logo">
        <div>
          <p>Generated by: <strong>
            <?php
              $user_id = $_SESSION['user_id'];
        
              $sql= "SELECT * FROM users WHERE user_id = $user_id";
              $result = $conn->query($sql);
      
              while ($row = $result->fetch_assoc()) {
                  echo ''.$row['first_name']. " " .$row["last_name"].'</p>';
              }
            ?>
          </strong></p>
          <p>Generated on: <strong><?php echo date("Y-m-d H:i:s"); ?></strong></p>
        </div>
      </div>

      <h2>Sales Report</h2>

      <div class="filter">
        <form method="GET">
          <label>Start Date:
            <input type="date" name="start_date" value="<?php echo $startDate; ?>">
          </label>
          <label style="margin-left:15px;">End Date:
            <input type="date" name="end_date" value="<?php echo $endDateRaw; ?>">
          </label>
          <button type="submit">Filter</button>
        </form>
      </div>

      <div class="summary">
        <p><strong>Total Sales:</strong> RM <?php echo number_format($totalSales, 2); ?></p>
        <p><strong>Total Orders:</strong> <?php echo $totalOrders; ?></p>
      </div>

      <table>
        <thead>
          <tr>
            <th>Product ID</th>
            <th>Product Name</th>
            <th>Price Per Unit (RM)</th>
            <th>Quantity Sold</th>
            <th>Total Revenue (RM)</th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($salesData as $item): ?>
            <tr>
              <td><?php echo $item['product_id']; ?></td>
              <td><?php echo htmlspecialchars($item['product_name']); ?></td>
              <td><?php echo number_format($item['price'], 2); ?></td>
              <td><?php echo $item['quantity']; ?></td>
              <td><?php echo number_format($item['revenue'], 2); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      
      <a href="generate_pdf.php?start_date=<?php echo $startDate; ?>&end_date=<?php echo $endDate; ?>" target="_blank" class="download-btn">
        <button type="button">Export to PDF</button>
      </a>
    </div>
  </div>
</body>
</html>
