<?php
require '../../../vendor/autoload.php';
use Dompdf\Dompdf;

include '../../connect_db/config.php';
date_default_timezone_set('Asia/Kuala_Lumpur');

// Start session if not already started
if (session_status() == PHP_SESSION_NONE) {
  session_start();
}

if(isset($_SESSION['user_id'])){
  $user_id = $_SESSION['user_id'];
        
  $sql= "SELECT * FROM users WHERE user_id = $user_id";
  $result = $conn->query($sql);
      
  while ($row = $result->fetch_assoc()) {
      $name= $row['first_name']. " " .$row["last_name"];
  }
}

$startDate = $_GET['start_date'] ?? date('Y-m-01');
$endDateRaw = $_GET['end_date'] ?? date('Y-m-t');
$endDate = $endDateRaw . ' 23:59:59';

$sql = "SELECT o.order_id, o.order_at, p.product_id, p.product_name, oi.quantity, oi.price
        FROM orders o
        JOIN order_items oi ON o.order_id = oi.order_id
        JOIN product p ON oi.product_id = p.product_id
        WHERE o.order_at BETWEEN ? AND ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $startDate, $endDate);
$stmt->execute();
$result = $stmt->get_result();

$salesData = [];
$totalSales = 0;
$orderIDs = [];

while ($row = $result->fetch_assoc()) {
    $pid = $row['product_id'];
    $pname = $row['product_name'];
    $amount = $row['quantity'] * $row['price'];

    if (!isset($salesData[$pid])) {
      $salesData[$pid] = [
          'product_id' => $pid,
          'product_name' => $pname,
          'price' => $row['price'],
          'quantity' => 0,
          'revenue' => 0
        ];
      }

    $salesData[$pid]['quantity'] = ($salesData[$pid]['quantity'] ?? 0) + $row['quantity'];
    $salesData[$pid]['revenue'] = ($salesData[$pid]['revenue'] ?? 0) + $amount;

    

    $totalSales += $amount;
    $orderIDs[$row['order_id']] = true;
}
$totalOrders = count($orderIDs);

$imgData = base64_encode(file_get_contents('../../upload/VeroSports.jpeg'));

$html = '
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      font-family: Arial, sans-serif;
      padding: 40px;
      background: #fff;
      font-size: 14px;
    }
    .report-box {
      background: white;
      padding: 30px;
      border-radius: 10px;
      box-shadow: 0 0 10px #ccc;
    }
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      border-bottom: 2px solid #000;
      padding-bottom: 10px;
    }
    .header img {
      height: 60px;
      boder-radius:10px;
    }
    h2 {
      margin-top: 20px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    table th{
      background-color: lightgray;
    }
    table th, table td {
      border: 1px solid gray;
      padding: 10px;
      text-align: left;
    }
    .summary {
      margin-top: 20px;
    }
    .filter {
      margin-bottom: 20px;
    }
  </style>
</head>
<body>
  <div class="report-box">
    <div class="header">
      <img src="data:image/jpeg;base64,' . $imgData . '" alt="Logo">
      <div>
        <p><strong>Generated by:</strong> '.$name.'</p>
        <p><strong>Generated on:</strong> ' . date("Y-m-d H:i:s") . '</p>
      </div>
    </div>

    <h2>VeroSports Sales Report</h2>
    <p><strong>From:</strong> ' . htmlspecialchars($_GET['start_date']) . ' <strong>   To:</strong> ' . htmlspecialchars($_GET['end_date']) . '</p>

    <div class="summary">
      <p><strong>Total Sales:</strong> RM ' . number_format($totalSales, 2) . '</p>
      <p><strong>Total Orders:</strong> ' . $totalOrders . '</p>
    </div>

    <table>
      <thead>
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>Price Per Unit (RM)</th>
          <th>Quantity Sold</th>
          <th>Total Revenue (RM)</th>
        </tr>
      </thead>
      <tbody>';

      foreach ($salesData as $data) {
        $html .= '
            <tr>
              <td>' . $data['product_id'] . '</td>
              <td>' . htmlspecialchars($data['product_name']) . '</td>
              <td>' . number_format($data['price'], 2) . '</td>
              <td>' . $data['quantity'] . '</td>
              <td>' . number_format($data['revenue'], 2) . '</td>
            </tr>';
    }

$html .= '
      </tbody>
    </table>
  </div>
</body>
</html>';


$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("sales_report_" . date("Ymd_His") . ".pdf", ["Attachment" => true]);
?>
